// apps/cli/template/with-auth/apps/web-react-router/src/routes/dashboard.tsx
import { authClient } from "@/lib/auth-client";
import { trpc } from "@/utils/trpc";
import { useQuery } from "@tanstack/react-query";
import { useEffect } from "react";
import { useNavigate } from "react-router";

export default function Dashboard() {
  const { data: session, isPending } = authClient.useSession();
  const navigate = useNavigate();

  const privateData = useQuery(trpc.privateData.queryOptions());

  useEffect(() => {
    if (!session && !isPending) {
      navigate("/login");
    }
  }, [session, isPending]);

  if (isPending) {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <h1>Dashboard</h1>
      <p>Welcome {session?.user.name}</p>
      <p>privateData: {privateData.data?.message}</p>
    </div>
  );
}

// apps/cli/templates/auth/web/nuxt/app/pages/dashboard.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'
const {$authClient} = useNuxtApp()

definePageMeta({
  middleware: ['auth']
})

const { $orpc } = useNuxtApp()

const session = $authClient.useSession()

const privateData = useQuery($orpc.privateData.queryOptions())

</script>

<template>
  <div class="container mx-auto p-4">
      <h1 class="text-2xl font-bold mb-4">Dashboard</h1>
     <div v-if="session?.data?.user">
        <p class="mb-2">Welcome {{ session.data.user.name }}</p>
     </div>
        <div v-if="privateData.status.value === 'pending'">Loading private data...</div>
        <div v-else-if="privateData.status.value === 'error'">Error loading private data: {{ privateData.error.value?.message }}</div>
        <p v-else-if="privateData.data.value">Private Data: {{ privateData.data.value.message }}</p>
  </div>
</template>
