// apps/cli/template/with-auth/apps/web-tanstack-start/src/routes/dashboard.tsx
import { authClient } from "@/lib/auth-client";
import { useTRPC } from "@/utils/trpc";
import { useQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { useEffect } from "react";

export const Route = createFileRoute("/dashboard")({
  component: RouteComponent,
});

function RouteComponent() {
  const navigate = Route.useNavigate();
  const trpc = useTRPC();
  const { data: session, isPending } = authClient.useSession();

  const privateData = useQuery(trpc.privateData.queryOptions());

  useEffect(() => {
    if (!session && !isPending) {
      navigate({
        to: "/login",
      });
    }
  }, [session, isPending]);

  if (isPending) {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <h1>Dashboard</h1>
      <p>Welcome {session?.user.name}</p>
      <p>privateData: {privateData.data?.message}</p>
    </div>
  );
}

// apps/cli/templates/auth/web/solid/src/routes/dashboard.tsx
import { authClient } from "@/lib/auth-client";
import { orpc } from "@/utils/orpc";
import { useQuery } from "@tanstack/solid-query";
import { createFileRoute } from "@tanstack/solid-router";
import { createEffect, Show } from "solid-js";

export const Route = createFileRoute("/dashboard")({
  component: RouteComponent,
});

function RouteComponent() {
  const session = authClient.useSession();
  const navigate = Route.useNavigate();

  const privateData = useQuery(() => orpc.privateData.queryOptions());

  createEffect(() => {
    if (!session().data && !session().isPending) {
      navigate({
        to: "/login",
      });
    }
  });

  return (
    <div>
      <Show when={session().isPending}>
        <div>Loading...</div>
      </Show>

      <Show when={!session().isPending && session().data}>
        <h1>Dashboard</h1>
        <p>Welcome {session().data?.user.name}</p>
        <p>privateData: {privateData.data?.message}</p>
      </Show>
    </div>
  );
}
